apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jat3ru33c-nodejs
  janus-idp.io/tekton: jat3ru33c-nodejs
  backstage.io/kubernetes-id: jat3ru33c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jat3ru33c-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
